server:
  port: 8080

evolution:
  api:
    url: http://localhost:3000
    instance: evolution
    token: 429683C4C977415CAAFCCE10F7D57E11

logging:
  level:
    root: INFO
    br.com.chatbot: DEBUG

prompt:
  classificacao:
    path: classpath:prompts/classificacao.txt

ia:
  tipo: openrouter
  openrouter:
    api:
      key: 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
  chatgpt:
    api:
      key: ${CHATGPT_API_KEY:sua-chave-aqui}